#!/bin/sh
# $1 = exit code (256 if killed by signal), $2 = signal number when $1=256
EXIT_CODE=$1
SIGNAL=$2
if [ "${EXIT_CODE}" -eq 256 ]; then
    printf "[SUPERVISOR] Service amuled was killed by signal %d.\n" "${SIGNAL}"
elif [ "${EXIT_CODE}" -ne 0 ]; then
    printf "[SUPERVISOR] Service amuled terminated with exit code: %d.\n" "${EXIT_CODE}"
else
    printf "[SUPERVISOR] Service amuled exited with code 0.\n"
fi
