#!/bin/sh

printf "[SUPERVISOR] Waiting 5 s before starting amuleweb service ...\n"
sleep 5
printf "[SUPERVISOR] Starting amuleweb service ...\n"
exec su-exec "${AMULE_USER}" amuleweb --amule-config-file="${AMULE_CONF}"
